package com.seoulmilk.invoice.application;

import com.seoulmilk.core.infrastructure.security.CustomUserDetails;
import com.seoulmilk.invoice.application.exception.InvoiceErrorCode;
import com.seoulmilk.invoice.domain.value.FileMetaData;
import com.seoulmilk.invoice.infrastructure.properties.InvoiceMockProperties;
import com.seoulmilk.receipt.dto.request.OcrValidationRequest;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.IntStream;

@Component
@RequiredArgsConstructor
public class InvoiceRequestAssembler {
    private final InvoiceMockProperties invoiceMockProperties;

    public Long resolveEmpPk(CustomUserDetails customUserDetails) {
        return customUserDetails != null ? customUserDetails.getId() : 1L;
    }

    public List<OcrValidationRequest> toQueueEvents(Long empPk, List<MultipartFile> files) {
        if (files == null || files.isEmpty()) {
            return createAutoGeneratedQueueEvents(empPk);
        }

        validateFiles(files);
        return files.stream()
                .map(file -> new OcrValidationRequest(
                        empPk,
                        createQueueFileUrl(file),
                        null
                ))
                .toList();
    }

    private void validateFiles(List<MultipartFile> files) {
        for (MultipartFile file : files) {
            if (file == null || file.isEmpty()) {
                throw InvoiceErrorCode.EMPTY_FILE.toException();
            }
            String filename = Objects.toString(file.getOriginalFilename(), "");
            new FileMetaData(filename, file.getContentType());
        }
    }

    private List<OcrValidationRequest> createAutoGeneratedQueueEvents(Long empPk) {
        int min = Math.max(1, invoiceMockProperties.getMinAutoFileCount());
        int max = Math.max(min, invoiceMockProperties.getMaxAutoFileCount());
        int count = ThreadLocalRandom.current().nextInt(min, max + 1);

        return IntStream.range(0, count)
                .mapToObj(i -> new OcrValidationRequest(
                        empPk,
                        "mock://invoice/autogen/" + UUID.randomUUID() + "/generated-" + (i + 1) + ".png",
                        null
                ))
                .toList();
    }

    private String createQueueFileUrl(MultipartFile file) {
        String originalFilename = Objects.toString(file.getOriginalFilename(), "unknown");
        return "mock://invoice/" + UUID.randomUUID() + "/" + originalFilename;
    }
}
